{SCAN_FOLDER .}
INCLUDE= -I../../include -I../../include/primitives -I../../include/templates -I../../include/png -I../../include/tga -I../../include/extra -I../../include/config 
PLATFORM = {PLATFORM}
TYPE =  {TYPE}

EXECUTABLE = tests-resource

ifeq ($(PLATFORM),WIN32)
INCLUDE += -I"$(FREETYPE_INCLUDE)" -I"$(FREETYPE_INCLUDE)/../" -I"$(FREETYPE_INCLUDE)/freetype/"
else
INCLUDE += -I"/usr/include/freetype" -I"/usr/include/freetype2"
endif

ifeq ($(PLATFORM),WIN32)
LDFLAGS= -L../../lib -lsaddy-$(TYPE) -lm -lopengl32  -lglu32 -lkernel32 -luser32 -lgdi32 -lwinspool  -lshell32 -lcomdlg32 -ladvapi32 -O2 -L"$(FREETYPE_LIB)" -lfreetype
DEFINES  = -DWIN32 -DMINGW
OUTPUT   = ../../bin/$(EXECUTABLE)-$(TYPE).exe
else
LDFLAGS= -L../../lib -lsaddy-$(TYPE) -L/usr/X11R6/lib -lm -lrt -lGL -lGLU -lpthread -lX11 -lfreetype
DEFINES  = -DUNIX -DLINUX -DGCC
OUTPUT   = ../../bin/$(EXECUTABLE)-$(TYPE)
endif

ifeq ($(TYPE),debug)
CCOPTS = -g
else
CCOPTS = -O2
endif

BUILD    = {FOR_EACH build/{NAME}_$(TYPE).o \s}
all: build ../../lib/libsaddy-$(TYPE).a $(OUTPUT)
build:
	mkdir build
../../lib/libsaddy-$(TYPE).a:
	echo "You forgot to build a library!"
$(OUTPUT): {FOR_EACH build/{NAME}_$(TYPE).o \s}
	g++ $(BUILD)   $(CCOPTS)  -o  $(OUTPUT)    $(LDFLAGS)
{FOR_EACH build/{NAME}_$(TYPE).o:\s{SOURCE}\n\tg++\s-c\s$(CCOPTS)\s{SOURCE}\s-o\sbuild/{NAME}_$(TYPE).o\s$(INCLUDE)\s$(DEFINES) \n}
clean:
ifeq ($(PLATFORM),WIN32)
	rd /s/q "build/*"
	del "$(OUTPUT)"
else
	rm -r ".build/*"
	rm "$(OUTPUT)"
endif
.PHONY: all clean