######################################################################
# Automatically generated by qmake (2.01a) Sat May 11 14:57:56 2013
######################################################################

TEMPLATE = app
TARGET = exporter
DEPENDPATH += .
INCLUDEPATH += .
DESTDIR = ../../bin
CONFIG += qt console
CONFIG += debug_and_release
# Input
SOURCES += main.cpp

CONFIG(debug, debug|release) {
    TARGET = exporter-debug
} else {
    TARGET = exporter-release
}
